/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ["class"],
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'sans-serif'],
                mono: ['JetBrains Mono', 'monospace'],
                headline: ['Inter', 'sans-serif'],
                body: ['Inter', 'sans-serif'],
                label: ['Inter', 'sans-serif'],
            },
            colors: {
                "surface-dim": "#dcd9d9",
                "surface-tint": "#b91a24",
                "error-container": "#ffdad6",
                "tertiary-fixed-dim": "#c7c6c6",
                "surface-container-low": "#f6f3f2",
                "surface-container-highest": "#e4e2e1",
                "outline": "#8f6f6d",
                "on-error-container": "#93000a",
                "inverse-surface": "#303030",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed": "#d8e2ff",
                "secondary-fixed-dim": "#adc6ff",
                "primary-fixed": "#ffdad7",
                "secondary": "#0058be",
                "on-tertiary-fixed-variant": "#464747",
                "surface-container-high": "#eae7e7",
                "on-surface-variant": "#5b403e",
                "on-tertiary": "#ffffff",
                "tertiary-fixed": "#e3e2e2",
                "on-primary-fixed": "#410004",
                "inverse-on-surface": "#f3f0ef",
                "on-secondary-container": "#fefcff",
                "surface-container": "#f0eded",
                "surface-bright": "#fcf9f8",
                "on-secondary-fixed": "#001a42",
                "tertiary": "#5b5c5c",
                "on-tertiary-container": "#fefcfc",
                "error": "#ba1a1a",
                "on-primary-container": "#fffbff",
                "on-error": "#ffffff",
                "on-surface": "#1b1c1c",
                "outline-variant": "#e4beba",
                "on-primary": "#ffffff",
                "tertiary-container": "#747474",
                "surface": "#fcf9f8",
                "secondary-container": "#2170e4",
                "background": "#fcf9f8",
                "on-secondary-fixed-variant": "#004395",
                "on-tertiary-fixed": "#1b1c1c",
                "surface-variant": "#e4e2e1",
                "inverse-primary": "#ffb3ad",
                "primary-fixed-dim": "#ffb3ad",
                "primary-container": "#da3437",
                "on-background": "#1b1c1c",
                "on-primary-fixed-variant": "#930013",
                "on-secondary": "#ffffff",
                "primary": "#b61722"
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            }
        },
    },
    plugins: [],
}
